version = 1

test_patterns = ["tests/**"]

exclude_patterns = ["vendor/**"]

[[analyzers]]
name = "php"
enabled = true

  [analyzers.meta]
  skip_doc_coverage = ["magic", "nonpublic"]

[[transformers]]
name = "php-cs-fixer"
enabled = true
